; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32doit-devkit-v1]
platform = espressif32@6.13.0
board = esp32doit-devkit-v1
framework = arduino
[env:esp32dev]
platform = espressif32@6.13.0
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    h2zero/NimBLE-Arduino@^2.1.0

build_flags =
    -D CORE_DEBUG_LEVEL=0
custom_export_build_info = yes
extra_scripts = post:scripts/export_versions.py
custom_build_info_section = build_info

; ===== AUTO EXPORTED BUILD INFO BEGIN =====
; env = esp32dev
; export_time = 2026-03-26 19:22:21
;
; build meta
; build_start_time = 2026-03-26 19:22:05
; build_end_time = 2026-03-26 19:22:21
; build_duration = 15.926 s
;
; hardware info
; hardware_board = esp32dev
; hardware_board_name = Espressif ESP32 Dev Module
; hardware_mcu = esp32
; hardware_cpu_freq = 240000000L
; hardware_flash_max = 4194304 bytes (4.00 MB)
; hardware_ram_max = 327680 bytes (320.00 KB)
; hardware_eeprom = N/A (ESP32 uses flash/NVS, no dedicated hardware EEPROM)
; hardware_psram = Unknown / not declared in board manifest
;
; build resource usage
; build_flash_used = 609520 bytes (595.23 KB)
; build_flash_total = 1310720 bytes (1.25 MB)
; build_flash_percent = 46.5%
; build_ram_total = 327680 bytes (320.00 KB)
;
; partition table
; partition_file = Not found
; partition = No entries parsed
;
; resolved platform
; platform_resolved = Platform espressif32@6.13.0 (required: espressif32 @ 6.13.0)
;
; resolved lib_deps
; lib_dep_resolved = NimBLE-Arduino@2.4.0 (required: h2zero/NimBLE-Arduino @ ^2.1.0)
;
; resolved platform_packages
; platform_package_resolved = framework-arduinoespressif32@3.20017.241212+sha.dcc1105b (required: platformio/framework-arduinoespressif32 @ ~3.20017.0)
; platform_package_resolved = tool-esptoolpy@2.41100.0 (required: platformio/tool-esptoolpy @ ~2.41100.0)
; platform_package_resolved = tool-mkfatfs@2.0.1 (required: platformio/tool-mkfatfs @ ~2.0.0)
; platform_package_resolved = tool-mklittlefs@1.203.210628 (required: platformio/tool-mklittlefs @ ~1.203.0)
; platform_package_resolved = tool-mkspiffs@2.230.0 (required: platformio/tool-mkspiffs @ ~2.230.0)
; platform_package_resolved = toolchain-riscv32-esp@8.4.0+2021r2-patch5 (required: espressif/toolchain-riscv32-esp @ 8.4.0+2021r2-patch5)
; platform_package_resolved = toolchain-xtensa-esp32@8.4.0+2021r2-patch5 (required: espressif/toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5)
; ===== AUTO EXPORTED BUILD INFO END =====
